from django.urls import path
from recordPage import views

urlpatterns = [
    path(
        'case/<int:caseNumber>',
        views.CaseView.as_view(),
        name='case'
    ),
    path(
        'case_list',
        views.CaseViewAll.as_view(),
        name='case-all'
    ),
    path(
        '',
        views.hi,
        name='hi'
    ),
    path(
        'case_create',
        views.CaseCreate,
        name='case-create'
    ),
    path(
        'delete/<pk>',
        views.CaseDelete.as_view(),
        name='case-delete'
    ),
    path(
        'update/<caseNumber>',
        views.CaseUpdate,
        name='case-update'
    ),
    path(
        '<int:caseNumber>/location_create',
        views.LocationCreate,
        name='location-create'
    ),
    path(
        'location_delete/<pk>',
        views.LocationDelete.as_view(),
        name='location-delete'
    ),
    path(
        'location_update/<pk>',
        views.LocationUpdate,
        name='location-update'
    ),
    path(
        'location_cache_create/<redirectType>/<pkOrCaseNumber>',
        views.LocationCacheCreate,
        name='location-cache-create'
    ),
]
